# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\stone\stone2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(640, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Btn_num1 = QtWidgets.QLabel(Form)
        self.Btn_num1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Btn_num1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Btn_num1.setObjectName("Btn_num1")
        self.horizontalLayout_4.addWidget(self.Btn_num1)
        self.Btn_num2 = QtWidgets.QLabel(Form)
        self.Btn_num2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Btn_num2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Btn_num2.setObjectName("Btn_num2")
        self.horizontalLayout_4.addWidget(self.Btn_num2)
        self.Btn_num3 = QtWidgets.QLabel(Form)
        self.Btn_num3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Btn_num3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Btn_num3.setObjectName("Btn_num3")
        self.horizontalLayout_4.addWidget(self.Btn_num3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Btn_OK = QtWidgets.QPushButton(Form)
        self.Btn_OK.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Btn_OK.setObjectName("Btn_OK")
        self.horizontalLayout_3.addWidget(self.Btn_OK)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_input1 = QtWidgets.QLineEdit(Form)
        self.Btn_input1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Btn_input1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Btn_input1.setObjectName("Btn_input1")
        self.horizontalLayout_2.addWidget(self.Btn_input1)
        self.Btn_input2 = QtWidgets.QLineEdit(Form)
        self.Btn_input2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Btn_input2.setObjectName("Btn_input2")
        self.horizontalLayout_2.addWidget(self.Btn_input2)
        self.Btn_input3 = QtWidgets.QLineEdit(Form)
        self.Btn_input3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Btn_input3.setObjectName("Btn_input3")
        self.horizontalLayout_2.addWidget(self.Btn_input3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Btn_num4 = QtWidgets.QLabel(Form)
        self.Btn_num4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Btn_num4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Btn_num4.setObjectName("Btn_num4")
        self.horizontalLayout_5.addWidget(self.Btn_num4)
        self.Btn_num5 = QtWidgets.QLabel(Form)
        self.Btn_num5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Btn_num5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Btn_num5.setObjectName("Btn_num5")
        self.horizontalLayout_5.addWidget(self.Btn_num5)
        self.Btn_num6 = QtWidgets.QLabel(Form)
        self.Btn_num6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Btn_num6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Btn_num6.setObjectName("Btn_num6")
        self.horizontalLayout_5.addWidget(self.Btn_num6)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 5, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 3)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout_2.setRowStretch(2, 2)
        self.gridLayout_2.setRowStretch(3, 1)
        self.gridLayout_2.setRowStretch(4, 3)
        self.gridLayout_2.setRowStretch(5, 2)
        self.gridLayout_2.setRowStretch(6, 2)
        self.gridLayout_2.setRowStretch(7, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "catch_stone"))
        self.pushButton_2.setText(_translate("Form", "石头堆1数量："))
        self.pushButton.setText(_translate("Form", "石头堆2数量："))
        self.pushButton_3.setText(_translate("Form", "石头堆3数量："))
        self.Btn_num1.setText(_translate("Form", "TextLabel"))
        self.Btn_num2.setText(_translate("Form", "TextLabel"))
        self.Btn_num3.setText(_translate("Form", "TextLabel"))
        self.Btn_OK.setText(_translate("Form", "确认"))
        self.label.setText(_translate("Form", "玩家面临的状态："))
        self.Btn_num4.setText(_translate("Form", "TextLabel"))
        self.Btn_num5.setText(_translate("Form", "TextLabel"))
        self.Btn_num6.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "要取走的石头数："))
        self.label_3.setText(_translate("Form", "玩家上一次的状态："))

