# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\stone\stone.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(640, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.Btn_input2 = QtWidgets.QLineEdit(Form)
        self.Btn_input2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Btn_input2.setObjectName("Btn_input2")
        self.horizontalLayout_2.addWidget(self.Btn_input2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Btn_firsthand = QtWidgets.QRadioButton(Form)
        self.Btn_firsthand.setEnabled(True)
        self.Btn_firsthand.setMaximumSize(QtCore.QSize(95, 16777215))
        self.Btn_firsthand.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_firsthand.setAutoFillBackground(False)
        self.Btn_firsthand.setObjectName("Btn_firsthand")
        self.horizontalLayout_3.addWidget(self.Btn_firsthand)
        self.Btn_secondhand = QtWidgets.QRadioButton(Form)
        self.Btn_secondhand.setMaximumSize(QtCore.QSize(95, 16777215))
        self.Btn_secondhand.setObjectName("Btn_secondhand")
        self.horizontalLayout_3.addWidget(self.Btn_secondhand)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.Btn_input1 = QtWidgets.QLineEdit(Form)
        self.Btn_input1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Btn_input1.setObjectName("Btn_input1")
        self.horizontalLayout.addWidget(self.Btn_input1)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Btn_OK = QtWidgets.QPushButton(Form)
        self.Btn_OK.setMaximumSize(QtCore.QSize(50, 30))
        self.Btn_OK.setObjectName("Btn_OK")
        self.gridLayout_4.addWidget(self.Btn_OK, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.Btn_input3 = QtWidgets.QLineEdit(Form)
        self.Btn_input3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Btn_input3.setObjectName("Btn_input3")
        self.horizontalLayout_4.addWidget(self.Btn_input3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout_2.setRowStretch(2, 2)
        self.gridLayout_2.setRowStretch(3, 2)
        self.gridLayout_2.setRowStretch(4, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "catch_stone"))
        self.pushButton_5.setText(_translate("Form", "石头堆2数量"))
        self.Btn_firsthand.setText(_translate("Form", "先手"))
        self.Btn_secondhand.setText(_translate("Form", "后手"))
        self.pushButton_4.setText(_translate("Form", "石头堆1数量"))
        self.Btn_OK.setText(_translate("Form", "确认"))
        self.pushButton.setText(_translate("Form", "石头堆3数量"))

